export const MESSAGE = {
  ALL_MESSAGE: 'ALL_MESSAGE',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECIEVE_MESSAGE: 'RECIEVE_MESSAGE',
  REMOVE_MESSAGE: 'REMOVE_MESSAGE',
  UPDATE_MESSAGE: 'UPDATE_MESSAGE',
};

export const MESSAGE_GROUP = {
  SEND_MESSAGE: 'SEND_MESSAGE_GROUP',
  RECIEVE_MESSAGE_GROUP: 'RECIEVE_MESSAGE_GROUP',
  REMOVE_MESSAGE_GROUP: 'REMOVE_MESSAGE_GROUP',
  UPDATE_MESSAGE_GROUP: 'UPDATE_MESSAGE_GROUP',
};
